import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';
import { preview } from 'vite';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const PORT = 4181;
const WARMUP_CYCLES = 2;
const MEASURED_CYCLES = 4;

const server = await preview({ root, preview: { port: PORT, strictPort: true } });
const browser = await chromium.launch({
  args: [
    '--js-flags=--expose-gc',
    '--ignore-gpu-blocklist',
    '--enable-gpu',
    ...(process.platform === 'win32' ? ['--use-angle=d3d11'] : []),
  ],
});

try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
  const cdp = await page.context().newCDPSession(page);
  await page.goto(`http://localhost:${PORT}/?e2e=1&seed=11&invulnerable=1&latency=0&clock=manual`);

  const snapshotByType = async () => {
    await page.evaluate(() => window.gc?.());
    const chunks = [];
    const onChunk = (event) => chunks.push(event.chunk);
    cdp.on('HeapProfiler.addHeapSnapshotChunk', onChunk);
    await cdp.send('HeapProfiler.takeHeapSnapshot', { reportProgress: false });
    cdp.off('HeapProfiler.addHeapSnapshotChunk', onChunk);
    const snapshot = JSON.parse(chunks.join(''));
    const { node_fields: fields, node_types: nodeTypes } = snapshot.snapshot.meta;
    const typeIndex = fields.indexOf('type');
    const sizeIndex = fields.indexOf('self_size');
    const totals = new Map();
    for (let i = 0; i < snapshot.nodes.length; i += fields.length) {
      const type = nodeTypes[0][snapshot.nodes[i + typeIndex]];
      totals.set(type, (totals.get(type) ?? 0) + snapshot.nodes[i + sizeIndex]);
    }
    return totals;
  };

  const playCycle = async () => {
    await page.getByRole('button', { name: 'Play', exact: true }).click();
    await page.getByRole('button', { name: 'Set sail' }).click();
    await page.waitForFunction(() => window.__pirateBattle !== undefined);
    await page.keyboard.down('Space');
    await page.keyboard.down('KeyD');
    await page.evaluate(() => {
      window.__pirateBattle?.advance(10);
    });
    await page.keyboard.up('Space');
    await page.keyboard.up('KeyD');
    await page.waitForTimeout(500);
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Main menu' }).click();
    await page.waitForTimeout(500);
  };

  for (let i = 0; i < WARMUP_CYCLES; i += 1) await playCycle();
  const before = await snapshotByType();
  for (let i = 0; i < MEASURED_CYCLES; i += 1) await playCycle();
  const after = await snapshotByType();

  const rows = [...after.entries()]
    .map(([type, size]) => ({
      type,
      deltaKb: Math.round(((size - (before.get(type) ?? 0)) / 1024) * 10) / 10,
    }))
    .sort((a, b) => b.deltaKb - a.deltaKb);
  const markdown = [
    '# Heap growth by node type',
    '',
    `Retained heap after a forced GC, compared between cycle ${WARMUP_CYCLES} and cycle ${WARMUP_CYCLES + MEASURED_CYCLES} of start, play and exit. Generated by \`npm run profile:heap\`.`,
    '',
    '| V8 node type | Delta (KB) |',
    '| --- | --- |',
    ...rows.map((row) => `| ${row.type} | ${row.deltaKb} |`),
    '',
  ].join('\n');

  await mkdir(join(root, 'docs', 'performance'), { recursive: true });
  await writeFile(join(root, 'docs', 'performance', 'HEAP-DIFF.md'), markdown);
  console.log(markdown);
} finally {
  await browser.close();
  await server.close();
}
